#!/usr/bin/env ruby
# example Ruby class to use Commerce API 
# http://developer.nikedev.com/blueprint?mdurl=http%3A%2F%2Fstash.nikedev.com%2Fprojects%2FCA%2Frepos%2Fcommerce-api%2Fbrowse%2FREADME.md%3Fraw
# hacklikeagirl 1.0
# @author ann wallae

require 'rubygems'
require 'pp'
require 'json'
require 'httparty'

class NikeCommerce
	include HTTParty
	base_uri 'http://commerce-api.nike.com'

	def initialize(client)
		@client = client
	end

	def get_product_inventory(id)
		self.class.get("/commerce/v1/us/en_US/product/#{id}/inventory.json?client=#{@client}")
	end

	def get_product_family(id)
		self.class.get("/commerce/v1/us/en_US/product/#{id}/family.json?client=#{@client}")
	end

	def get_product_details(id)
		self.class.get("/commerce/v1/us/en_US/product/#{id}/details.json?client=#{@client}")
	end

	def get_product_recommendations(id)
		self.class.get("/commerce/v1/us/en_US/product/#{id}/recommendations.json?client=#{@client}")
	end

	def get_product_review(id)
		self.class.get("/commerce/v1/us/en_US/product/#{id}/reviews.json?client=#{@client}")
	end

	def get_multi_products(*ids)
		self.class.get("/commerce/v1/us/en_US/product/details.json?ids=#{ids.join(",")}&store=false&online=true&includePreLaunch=false&client=#{@client}")
	end

	def search(query)
		self.class.get("/commerce/v1/us/en_US/search.json?query=#{query}&client=#{@client}")
	end

end

def put_line
	puts "--------------------------------------------------"
end

# examples on using th class and apis
commerce = NikeCommerce.new('hacklikeagirl')

#pp commerce.get_product_inventory('828330')
#pp commerce.get_product_recommendations('1553922')

# search for tights and dispaly images
tights = commerce.search('tights')
tights_parsed = JSON.parse(tights.body)
tights_parsed["results"].each do |t| 
	puts t["images"].first["path"]
end
put_line

# search for hoodie and get the reviews
hoodies = commerce.search('hoodie')
hoodies_parsed = JSON.parse(hoodies.body)
hoodies_parsed["results"].each do |h|
	reviews = commerce.get_product_review(h["id"])
	puts "Reviews for #{h["name1"]}"
	reviews_parsed = JSON.parse(reviews.body)
	reviews_parsed["reviews"].each do |r|
		puts "Rating: #{r["rating"]}"
		puts "Comment: #{r["text"]}"
	end
	put_line
end
